version: "3"
services:
  mongo:
    container_name: mongo
    image: "mongo:4.0"
    restart: always
    environment:
      MONGO_INITDB_DATABASE: salesmanager
    ports:
      - "27017:27017"
    expose:
      - "27017"